COMPONENT=EasyDisseminationAppC
### For Drip:
CFLAGS += -I$(TINYOS_OS_DIR)/lib/net -I$(TINYOS_OS_DIR)/lib/net/drip

CFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
### For DIP:
#CFLAGS += -I$(TINYOS_OS_DIR)/lib/net -I%T/lib/net/dip -I%T/lib/net/dip/interfaces
### For Dhv
#CFLAGS += -I$(TINYOS_OS_DIR)/lib/net -I%T/lib/net/dhv -I%T/lib/net/dhv/interfaces
include $(TINYOS_ROOT_DIR)/Makefile.include
