#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'MeasurementData'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 6

# The Active Message type associated with this message.
AM_TYPE = 137

class MeasurementData(tinyos.message.Message.Message):
    # Create a new MeasurementData of size 6.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=6):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <MeasurementData> \n"
        try:
            s += "  [rss=0x%x]\n" % (self.get_rss())
        except:
            pass
        try:
            s += "  [senderNodeId=0x%x]\n" % (self.get_senderNodeId())
        except:
            pass
        try:
            s += "  [receiverNodeId=0x%x]\n" % (self.get_receiverNodeId())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: rss
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'rss' is signed (False).
    #
    def isSigned_rss(self):
        return False
    
    #
    # Return whether the field 'rss' is an array (False).
    #
    def isArray_rss(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'rss'
    #
    def offset_rss(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'rss'
    #
    def offsetBits_rss(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'rss'
    #
    def get_rss(self):
        return self.getSIntElement(self.offsetBits_rss(), 16, 1)
    
    #
    # Set the value of the field 'rss'
    #
    def set_rss(self, value):
        self.setSIntElement(self.offsetBits_rss(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'rss'
    #
    def size_rss(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'rss'
    #
    def sizeBits_rss(self):
        return 16
    
    #
    # Accessor methods for field: senderNodeId
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'senderNodeId' is signed (False).
    #
    def isSigned_senderNodeId(self):
        return False
    
    #
    # Return whether the field 'senderNodeId' is an array (False).
    #
    def isArray_senderNodeId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'senderNodeId'
    #
    def offset_senderNodeId(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'senderNodeId'
    #
    def offsetBits_senderNodeId(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'senderNodeId'
    #
    def get_senderNodeId(self):
        return self.getUIntElement(self.offsetBits_senderNodeId(), 16, 1)
    
    #
    # Set the value of the field 'senderNodeId'
    #
    def set_senderNodeId(self, value):
        self.setUIntElement(self.offsetBits_senderNodeId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'senderNodeId'
    #
    def size_senderNodeId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'senderNodeId'
    #
    def sizeBits_senderNodeId(self):
        return 16
    
    #
    # Accessor methods for field: receiverNodeId
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'receiverNodeId' is signed (False).
    #
    def isSigned_receiverNodeId(self):
        return False
    
    #
    # Return whether the field 'receiverNodeId' is an array (False).
    #
    def isArray_receiverNodeId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'receiverNodeId'
    #
    def offset_receiverNodeId(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'receiverNodeId'
    #
    def offsetBits_receiverNodeId(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'receiverNodeId'
    #
    def get_receiverNodeId(self):
        return self.getUIntElement(self.offsetBits_receiverNodeId(), 16, 1)
    
    #
    # Set the value of the field 'receiverNodeId'
    #
    def set_receiverNodeId(self, value):
        self.setUIntElement(self.offsetBits_receiverNodeId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'receiverNodeId'
    #
    def size_receiverNodeId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'receiverNodeId'
    #
    def sizeBits_receiverNodeId(self):
        return 16
    
