#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'MeasurementData'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 4

# The Active Message type associated with this message.
AM_TYPE = 5

class MeasurementData(tinyos.message.Message.Message):
    # Create a new MeasurementData of size 4.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=4):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <MeasurementData> \n"
        try:
            s += "  [rss=0x%x]\n" % (self.get_rss())
        except:
            pass
        try:
            s += "  [nodeId=0x%x]\n" % (self.get_nodeId())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: rss
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'rss' is signed (False).
    #
    def isSigned_rss(self):
        return False
    
    #
    # Return whether the field 'rss' is an array (False).
    #
    def isArray_rss(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'rss'
    #
    def offset_rss(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'rss'
    #
    def offsetBits_rss(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'rss'
    #
    def get_rss(self):
        return self.getUIntElement(self.offsetBits_rss(), 16, 1)
    
    #
    # Set the value of the field 'rss'
    #
    def set_rss(self, value):
        self.setUIntElement(self.offsetBits_rss(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'rss'
    #
    def size_rss(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'rss'
    #
    def sizeBits_rss(self):
        return 16
    
    #
    # Accessor methods for field: nodeId
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'nodeId' is signed (False).
    #
    def isSigned_nodeId(self):
        return False
    
    #
    # Return whether the field 'nodeId' is an array (False).
    #
    def isArray_nodeId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'nodeId'
    #
    def offset_nodeId(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'nodeId'
    #
    def offsetBits_nodeId(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'nodeId'
    #
    def get_nodeId(self):
        return self.getUIntElement(self.offsetBits_nodeId(), 16, 1)
    
    #
    # Set the value of the field 'nodeId'
    #
    def set_nodeId(self, value):
        self.setUIntElement(self.offsetBits_nodeId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'nodeId'
    #
    def size_nodeId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'nodeId'
    #
    def sizeBits_nodeId(self):
        return 16
    
